(define (compile-program x)
  (define output-file (open-file "scheme_entry.s" "w"))
  (define (emit . format-args)
    (define (format-string . args)
      (apply simple-format (cons #f args)))
    (let ((output (apply format-string format-args)))
      (display output)
      (display output output-file)))
  (emit "\t.text\n")
  (emit "\t.globl scheme_entry\n")
  (emit "scheme_entry:\n")
  (emit "\tmovl $~a, %eax\n" x)
  (emit "\tret\n")
  (force-output)
  (close-port output-file))

(compile-program 42)
